name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release