on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .net core SDK\
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
  
